AUTHOR = 'bukovinian_forest'

VERSION = '0.1.5'

SCREEN_TITLE  = "()()((((()))))(()"
SCREEN_WIDTH  = 256
SCREEN_HEIGHT = 256

NUM_EXPLODE_BUBBLES = 11
MAX_BUBBLE_SPEED    = 4

INIT_MESSAGE      = "CLICK ON A FIRST CIRCLE"
ATTENTION_MESSAGE = "TO SLOW"
GAMEOVER_MESSAGE  = "YOU LOSE"
RESTART_MESSSAGE  = "CLICK ON A SCREEN TO RESTART"

GUI_STAGE_TEXT = "STAGE"

NUM_BONUS_SECONDS = 6
